#!/usr/bin/env python3
"""
    mkalias.py - CLI app to create finder aliases./mk

"""

import argparse
import os

import osascript


def parse_args():
    parser = argparse.ArgumentParser(prog='mkalias',
                                     description='Application to create Finder aliases from the command line')

    parser.add_argument('source', help='Source to create alias from')
    parser.add_argument('destination', help='Destination directory of alias')
    parser.add_argument('-n', dest='alias_name', metavar="Name", help='Set the name of the new alias')

    return parser.parse_args()


def check_path(source, destination):
    path_exists = True
    source = os.path.abspath(source)
    destination_head, destination_tail = os.path.split(destination)

    def print_not_found_error(location):
        print("Error '{}' not found!".format(location))

        if not os.path.isdir(source):
            print_not_found_error(source)
            path_exists = False
        elif not os.path.isdir(destination_head):
            print_not_found_error(destination_head)
            path_exists = False
        if not os.path.isfile(source):
            print_not_found_error(source)
            path_exists = False
        elif not os.path.isdir(destination_head):
            print_not_found_error(destination_head)
            path_exists = False

    if path_exists:
        print("Source Dir - '{}'".format(source))
        print("Destination Dir - '{}'".format(destination))

    return path_exists


def create_alias(source, destination):
    command_string = 'tell application "Finder" to make alias file to POSIX file "{}" at POSIX file "{}"' \
        .format(source, destination)

    code, out, error = osascript.run(command_string)

    print(command_string)
    print(code)
    print(out)
    print(error)


def main():
    args = parse_args()

    source = os.path.abspath(args.source)
    destination = os.path.abspath(args.destination)

    check_path(source, destination)

    create_alias(source, destination)


if __name__ == "__main__":
    main()
